In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:

from google.colab import files
 
 
uploaded = files.upload()

Saving Social_Network_Ads.csv to Social_Network_Ads (1).csv


In [ ]:
data=pd.read_csv('Social_Network_Ads.csv');
new_data = { "Female":0,
             "Male":1,
              }
data= data.replace({"Gender":new_data})

In [ ]:
x=data.drop(['Purchased'],axis=True)
y=data['Purchased']

In [ ]:
x

User ID  Gender  Age  EstimatedSalary
0    15624510       1   19            19000
1    15810944       1   35            20000
2    15668575       0   26            43000
3    15603246       0   27            57000
4    15804002       1   19            76000
..        ...     ...  ...              ...
395  15691863       0   46            41000
396  15706071       1   51            23000
397  15654296       0   50            20000
398  15755018       1   36            33000
399  15594041       0   49            36000

[400 rows x 4 columns]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=True)

In [ ]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
cf=LogisticRegression(random_state=0)
cf.fit(x_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred=cf.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0])

In [ ]:
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[50  8]
 [11 31]]
0.81


In [ ]:
y_pred[:20]
y_test[:20]

398    0
125    0
328    1
339    1
172    0
342    0
197    0
291    1
29     0
284    0
174    0
372    0
188    0
324    1
321    1
227    1
371    1
5      0
78     0
223    1
Name: Purchased, dtype: int64

In [ ]:
cl1=cf.predict(([[15624510,0,30,87000]]))
cl1

array([0])